### ISSUE TITLE
Blog section

### ISSUE THREAD

**Issue by santychuy** [santychuycom/santychuy.com#5]
Implement the `/blog/[post]` page to show the each post that will live inside the `src/content` directory.

### TODOs

- [x] Deep dive to investigate how it works to manage this type of content on Astro
- [x] Take a decision if it's necessary to add any new deps/tools
- [x] Create the blog post page
- [x] Show the latest blog posts (in asc order) on the **Latest Post** section
- [x] Adapt correctly the SEO info for the blog posts
